version: '2'
services:
  nginx-php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'electrum-mock-php-nginx'
    ports:
      - '8000:80'
    volumes:
      - ./:/app
    environment:
      - ELECTRUM_BALANCE=0