version: '2'
services:
  nginx-php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'electrum-mock-php-nginx'
    ports:
      - '8050:80'
    volumes:
      - ./:/app
    environment:
      - ELECTRUM_BALANCE=0
      - ELECTRUM_ADDRESS_BALANCE_CONFIRMED=1.008
      - ELECTRUM_ADDRESS_BALANCE_UNCONFIRMED=0.004